### ISSUE TITLE
Feasibility of instantiating homomorphic encryption as SNARK circuit

### ISSUE THREAD

**Issue by jon-chuang** [scipr-lab/libiop#10]
Could someone give some opinions on the feasibility of instantiating a circuit for performing homomorphic function eval with known (encrypted) inputs as a SNARK?

That's because some of us from this world want some computational integrity guarantees in the multiparty setting when doing delegated, privacy-preserving computing. 

The reason we would want homomorphic encryption is that we would like to obscure inputs from the server (prover) performing the computations. For this reason, there is not really a strong requirement for zero-knowledge, since all inputs could be considered public, since they are encrypted anyway (although in practice it may be better to keep them private to leak less information, in case a private key gets leaked, for instance). However, there may be parts of our schemes such as encryption and decryption that could possibly be worth verifying for a multiparty protocol. 

We have deterministic circuits (no recursion and can unroll loops deterministically), operations involving modular arithmetic wrt prime moduli, number theoretic transform, data permutations. It is unclear that many of the optimisations seen in current implementations (SEAL, Lattigo, Palisade) such as RNS word size decompositions would be the right choices for a SNARK circuit. 

I would assume we would want some efficiency during setup, since we are passing different inputs to the same circuit, but each output given inputs must be verified independently. We would also prefer not to encounter any toxic waste. I have to think further about whether proof sizes are an issue by comparing it with average data transmission size per atomic circuit. 

Which of the available schemes might be best for our purposes?

**Comment by ValarDragon** [comment]
Sorry, didn't get around to responding to this sooner. Closing this for now, feel free to comment if you'd still like to continue a discussion. 

Most of the various (non-recursive) SNARKs right now can be thought of as mainly varying in two parameters, one is the intermediate representation they take as input, and the second is the cryptographic compiler they use to get a SNARK. (What compiler has the fastest prover for a given representation keeps on changing, the trust assumptions it requires don't)

The roughly 5 compilers you have are (and the works that explicitly use it):
* Transparent Setup, Post-Quantum - Fractal, AIR-STARK, Aurora, Ligero.
* Transparent DL based, linear verifier - Bulletproofs.
* Transparent Class group vector commitment based -  SuperSonics.
* Trusted Universal Setup - Marlin, Plonk, Sonic.
* Circuit specific trusted setup (This only supports R1CS) - Groth16, GM17. These are the fastest provers for R1CS atm.

Given that you want no toxic waste and not post-quantumness, then if you can tolerate linear verifiers, BulletProofs (slash anything obtained using that compiler) should be the fastest for your purpose.

I don't know your circuit well enough to know which of the two common intermediate representations (AIR / R1CS) would be better. However for almost all common circuits with repeated sub-structure that I'm aware of being interesitng, AIR provers outperform R1CS ones if you spend enough time optimizing the AIR constraint system.
