### ISSUE TITLE
using num_input not equal to power of two minus one causes exception

### ISSUE THREAD

**Issue by haochenuw** [scipr-lab/libiop#20]
Might be a trivial question -- in `test_aurora_snark` if I change the num_input to something which is not a power of two minus one, an `invalid_argument` is thrown. Is this due to the proof itself or just an implementation thing?

**Comment by ValarDragon** [comment]
Its an implementation thing. We should internally pad the constraint system to have 2^n - 1 inputs

**Comment by haochenuw** [comment]
Got it. Thanks!
