### ISSUE TITLE
BCS - Refactor hashchain logic, separate transcript into (BCS proof, BCS transcript)

### ISSUE THREAD

**Issue by ValarDragon** [scipr-lab/libiop#33]
Currently BCS transcripts dually mean both proofs and transcripts, in a way that is very confusing.

We should de-conflate these, and have the proof system output just a proof. The verifier then runs a method `run_hashchain(proof)` and gets a transcript.

Additionally, the logic for dealing with hashchains is quite scattered at the moment. We should package it together, to maximize code re-use and readability.

The verifier should just run the single `run_hashchain` method to get the transcript. The prover should have a method for `hashchain_absorb_round(mutative hashchain state, prover messages, MT roots)`, `hashchain_squeeze_outputs(mutative hashchain state, num outputs)` and `hashchain_squeeze_query_positions(mutative hashchain state, num_positions, domain_size_in_bits)`. 

`run_hashchain` then calls these as a sub-routine.

Organizationally, the sub-routine methods should all go in `bcs_common`, while the `run_hashchain` method should go in the verifier. At the moment, the equivalent of `run_hashchain` in the verifier is in the `seal_interactive_registrations` method.

**Comment by alexander-zw** [comment]
The function is `seal_interaction_registrations`

**Comment by alexander-zw** [comment]
Correction:

The logic for computing hashchains is duplicated in the prover and verifier (twice in the prover). We should package it together into a single function, `run_hashchain_for_round`, to maximize code re-use and readability.

Organizationally, the sub-routine methods should all go in bcs_common. At the moment, the equivalent of `run_hashchain_for_round` in the prover and verifier are in the inherited `seal_interaction_registrations` method.
