### ISSUE TITLE
prime fileld example in tests

### ISSUE THREAD

**Issue by xfu2006** [scipr-lab/libiop#40]
Could you give an example of using prime field in tests/test_aurora_snark.cpp? In addition to GF(64)?

**Comment by ValarDragon** [comment]
Thats already done in https://github.com/scipr-lab/libiop/blob/master/libiop/tests/snark/test_aurora_snark.cpp#L66!

**Comment by xfu2006** [comment]
Thanks again for the quick response!

Xiang

________________________________

**Comment by ValarDragon** [comment]
np!
